### ISSUE TITLE
Training Parameters

### ISSUE THREAD

**Issue by qiaoruiyt** [Noahs-ARK/soft_patterns#7]
Hello! Thank you for fixing the Linux issue. I have tried to train the soft pattern on SST 2-class dataset with default setting and the below setting (command-line) but I couldn't let the model learn (accuracy stays at around 0.5). 
```
-p 7-20_6-20_5-20_4-20_3-20_2-20 -i 100
```
May I know how am I suppose to train the model efficiently so that I can have a better interpretation on those patterns? Hopefully it's not due to training on Linux machine. Thank you!

**Comment by roys174** [comment]
Thanks for opening the issue!

I think the problem was the default value for the MLP hidden size was too small (10). I've updated it to 25 and it's learning fine with the number of patterns you specified.

I would also recommend using the max-times semiring (--maxtimes).

Please let me know if you still experiencing troubles training the model.

Best,
Roy

**Comment by qiaoruiyt** [comment]
Thank you Roy. It's awesome. The model is now learning properly!
